---
scenario:
  name: vagrant
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint

platforms:
# TODO Ubuntu doesn't include some python modules like lxml required by the health_check task
#- name: jee-molecule-ubuntu-18.04
#  box: ubuntu/bionic64 # 18.04
#  memory: 512
#  cpus: 1
- name: jee-molecule-centos-7
  box: centos/7
  memory: 512
  cpus: 1

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../converge.yaml

verifier:
  name: testinfra
  directory: ../tests/
  lint:
    name: flake8
  options:
    v: 1 # show which tests where executed in test output
